### ISSUE TITLE
Redimensionar

### ISSUE THREAD

**Issue by Cecilio10** [kondoSoft/creaturviajes.com#1]
- Redimensionar el logotipo de menú, al tamaño más grande presentado de las medias queries css
- Redimensionar imagenes e iconos, al tamaño más grande presentado de las medias queries css
- Adaptar el tamaño con css para el diseño responsivo

**Comment by JoJoCoJo** [comment]
### Avances y pendientes
- [x] Se redujo el tamaño de las imagenes
- [x] Adaptar al diseño responsivo
